map:
  test: 1

timeBetweenEvictionRunsMillis: 60000
minIdle: 10
maxActive: 50
maxWait: 60000

cqep:
  url: 127.0.0.1:8080/cqep

cqep2:
  url: 127.0.0.1:8081

ai:
  yuntai:
    ctrl: http://10.118.14.79:8000/PTZCtrl/position

jdbc:
  water:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://zhcq.f3322.net:3323/cqwater_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: cqwater
    password: cqwater123!@#
    minIdle: ${minIdle}
    maxActive: ${maxActive}
    maxWait: ${maxWait}
    timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
    initial-size: 10
    min-idle: 5
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 180
    test-while-idle: true
    validation-query: select 1
    test-on-borrow: true
    min-evictable-idle-time-millis: 600000
    time-between-eviction-runs-millis: 300000
  
sms:
  username: admin
  password: admin
  url: http://10.118.2.78:8090/api/sms/sendSms/

server:
  port: 8001
  servlet:
    context-path: /app
    session:
      timeout: 7200
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-threads: 500
    max-connections: 2000
    connection-timeout: 10000


shiro:
  usertable: user
  pwdname: spassword
  saccountname: saccountname
  userkey: id

spring:
  application:
    name: water-common
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      number_format: 0.##
  thymeleaf:
    prefix: classpath:/templates
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 10000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        min-idle: 1
        max-idle: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      
