cqep:
  url: 10.118.13.22:8080
file:
  upload:
    path: /usr/local/temp/
imgpath:
  path: file:Z:/
jdbc:
  shijuwater:
    jdbc-url: jdbc:mysql://10.118.13.22:3306/cqepw10?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root123456
    username: root
  water:
    jdbc-url: jdbc:mysql://localhost:3306/cqep_bishan?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: 123456
    username: root
logging:
  file: bishan.log
  level:
    root: error
  path: /log/pc/
server:
  port: 8001
sms:
  bishan:
    url: http://10.117.80.202:8082/sms/send
  issend: true
  password: admin
  url: http://10.118.2.78:8090/api/sms/sendSms/
  username: admin
spring:
  redis:
    host: 10.118.14.35
    jedis:
      pool:
        max-idle: 100
        min-idle: 10
super:
  admin:
    id: 111111
xcrw:
  imgupload:
    url: proxyImg/upload

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/